SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) `COUNT`
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY `COUNT` DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

################### RANK 함수 이용 ####################
SELECT D.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW C
JOIN (
    SELECT B.MEMBER_NAME, A.MEMBER_ID, A.REVIEW_TEXT, A.REVIEW_DATE, RANK() OVER(ORDER BY CNT DESC) RANKING
    FROM (
        SELECT *, COUNT(*) CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) A
    JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
) D
ON C.MEMBER_ID = D.MEMBER_ID
WHERE D.RANKING = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;

###################  ####################
# SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
# FROM REST_REVIEW A
# LEFT JOIN MEMBER_PROFILE B
# ON A.MEMBER_ID = B.MEMBER_ID
# WHERE A.MEMBER_ID = (
#     SELECT MEMBER_ID FROM (
#         SELECT A.MEMBER_ID MEMBER_ID, COUNT(*) NUM
#         FROM REST_REVIEW A
#         LEFT JOIN MEMBER_PROFILE B
#         ON A.MEMBER_ID = B.MEMBER_ID
#         GROUP BY MEMBER_ID
#         ORDER BY NUM DESC
#         LIMIT 1
#     ) T 
# )
# ORDER BY REVIEW_DATE;

#     SELECT COUNT(*)
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID;
