################# SOL1 ####################
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE "INTACT%" AND (O.SEX_UPON_OUTCOME LIKE "SPAYED%" OR O.SEX_UPON_OUTCOME LIKE "NEUTERED%")
ORDER BY ANIMAL_ID;

################# SOL2 ####################
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY ANIMAL_ID;

################# SOL3 ####################
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE "INTACT%" AND O.SEX_UPON_OUTCOME NOT LIKE "INTACT%"
ORDER BY ANIMAL_ID;
