SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, COUNT(DISTINCT S.USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT S.USER_ID) / (
    SELECT COUNT(*) 
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), 1) PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U
ON S.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
