SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW A
LEFT JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) C
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY C DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE;

# 틀린 답
# SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
# FROM REST_REVIEW A
# LEFT JOIN MEMBER_PROFILE B
# ON A.MEMBER_ID = B.MEMBER_ID
# WHERE A.MEMBER_ID = (
#     SELECT MEMBER_ID FROM (
#         SELECT A.MEMBER_ID MEMBER_ID, COUNT(*) NUM
#         FROM REST_REVIEW A
#         LEFT JOIN MEMBER_PROFILE B
#         ON A.MEMBER_ID = B.MEMBER_ID
#         GROUP BY MEMBER_ID
#         ORDER BY NUM DESC
#         LIMIT 1
#     ) T 
# )
# ORDER BY REVIEW_DATE;

#     SELECT COUNT(*)
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID;