################## SOL1 ###################
SELECT FLOOR(PRICE / 10000) * 10000 PRICE_GROUP, COUNT(PRODUCT_ID) PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;

################## SOL2 ###################
SELECT TRUNCATE(PRICE / 10000, 0) * 10000 PRICE_GROUP, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;

################## SOL3 ###################
SELECT TRUNCATE(PRICE, -4) PRICE_GROUP, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;