################## SOL1 ######################
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A, (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES FROM REST_INFO
    GROUP BY FOOD_TYPE
) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES
ORDER BY A.FOOD_TYPE DESC;

################## SOL2 ######################
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) T
ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC;